// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title BugPayVault
 * @notice Confidential Bug Bounty Escrow Vault integrated with Safe Multisig & iExec Nox TEE Enclaves.
 * @dev Verifies off-chain hardware ECDSA proof signatures generated by Nox TEE before releasing Sepolia ETH.
 */
contract BugPayVault {
    // Address of the authorized iExec Nox TEE Enclave Relayer key
    address public noxEnclaveRelayer;
    address public owner;

    // Total escrow balance managed by the vault
    uint256 public totalEscrowedBalance;

    // Mapping of bug hashes to claim status to prevent double-claiming
    mapping(bytes32 => bool) public claimedBugs;
    mapping(bytes32 => uint256) public bountyPools;

    // Events
    event EscrowDeposited(address indexed sender, bytes32 indexed bountyId, uint256 amount);
    event BountyReleased(bytes32 indexed bugHash, address indexed stealthRecipient, uint256 amount, uint256 timestamp);
    event NoxRelayerUpdated(address indexed oldRelayer, address indexed newRelayer);

    error UnauthorizedOwner();
    error InvalidNoxProofSignature();
    error BugAlreadyClaimed();
    error InsufficientVaultBalance();
    error PayoutTransferFailed();

    modifier onlyOwner() {
        if (msg.sender != owner) revert UnauthorizedOwner();
        _;
    }

    constructor(address _noxEnclaveRelayer) {
        owner = msg.sender;
        noxEnclaveRelayer = _noxEnclaveRelayer;
    }

    /**
     * @notice Allows Safe Multisig or DAO admins to fund a bug bounty pool.
     */
    function depositBountyPool(bytes32 bountyId) external payable {
        require(msg.value > 0, "Deposit must be > 0");
        bountyPools[bountyId] += msg.value;
        totalEscrowedBalance += msg.value;
        emit EscrowDeposited(msg.sender, bountyId, msg.value);
    }

    /**
     * @notice Releases bounty funds to a stealth burner wallet upon valid Nox TEE signature verification.
     * @param bugHash Keccak256 hash of the vulnerability report.
     * @param stealthRecipient Stealth burner wallet address receiving the payout.
     * @param amount Bounty payout amount in Wei.
     * @param v ECDSA signature v parameter from Nox TEE.
     * @param r ECDSA signature r parameter from Nox TEE.
     * @param s ECDSA signature s parameter from Nox TEE.
     */
    function claimBounty(
        bytes32 bugHash,
        address payable stealthRecipient,
        uint256 amount,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external {
        if (claimedBugs[bugHash]) revert BugAlreadyClaimed();
        if (address(this).balance < amount) revert InsufficientVaultBalance();

        // Reconstruct message hash signed by iExec Nox TEE Hardware Enclave
        bytes32 messageHash = keccak256(
            abi.encodePacked(bugHash, stealthRecipient, amount, block.chainid, address(this))
        );
        bytes32 ethSignedMessageHash = keccak256(
            abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash)
        );

        // Recover signer from signature
        address signer = ecrecover(ethSignedMessageHash, v, r, s);
        if (signer != noxEnclaveRelayer) revert InvalidNoxProofSignature();

        // Mark bug as claimed
        claimedBugs[bugHash] = true;
        totalEscrowedBalance -= amount;

        // Execute ETH transfer to stealth burner wallet
        (bool success, ) = stealthRecipient.call{value: amount}("");
        if (!success) revert PayoutTransferFailed();

        emit BountyReleased(bugHash, stealthRecipient, amount, block.timestamp);
    }

    /**
     * @notice Updates the authorized iExec Nox TEE Relayer address.
     */
    function setNoxRelayer(address _newRelayer) external onlyOwner {
        require(_newRelayer != address(0), "Invalid relayer");
        emit NoxRelayerUpdated(noxEnclaveRelayer, _newRelayer);
        noxEnclaveRelayer = _newRelayer;
    }

    receive() external payable {
        totalEscrowedBalance += msg.value;
    }
}
